### ISSUE TITLE
[30분] Docker 소개 (실습 위주)

### ISSUE THREAD

**Issue by whikwon** [kairproject/schedule#16]
Docker를 활용해서 간단하게 Dockerfile을 생성해서 다른 사람들이 만들어놓은 Dockerhub의 이미지를 pull 해오고 원하는 방식대로 환경을 셋업하는 방법까지 알려드립니다. 

사전 준비: 각 OS에 맞게 Docker 설치 필요. OS 별로 개별 이슈가 있을 것이기 때문에 설치가 안 된 경우는 참가가 어렵습니다.

**Comment by Curt-Park** [comment]
assignee 넣어주세요~

**Comment by whikwon** [comment]
감사합니다. assign 했습니다.

**Comment by whikwon** [comment]
실습에 참여하시는 분들은 정신 건강을 위해서 https://github.com/junegunn/fzf 를 설치해주세요. 
용도는 입력했던 command history 기억용입니다. 

말로 설명하면서 다 같이 따라서 해보는 식으로 진행할 거고 몸으로 익히는 느낌이라 되도록이면 어떤 문서를 보고 하는거보다 한 번 써보고 쳐봤던 명령어에서 찾아가는 식으로 해서 빠르게 익히시게 해드리겠습니다.

**Comment by whikwon** [comment]
실습 정리 내용: https://github.com/kairproject/examples/blob/master/docker/docker_tutorial.md
