### ISSUE TITLE
[15분] ROS 통신 구성

### ISSUE THREAD

**Issue by ysbsb** [kairproject/schedule#17]
ROS 통신 구성에 대한 전반적인 내용을 소개해드리려고 합니다.

중요한 3가지 내용은 다음과 같습니다.
1. Publisher 통신
2. Custom Message 작성하기
3. 좌표관련 tf, quaternion

되는데 까지 준비해보겠습니다.

**Comment by Curt-Park** [comment]
assignee 넣어주세요~
