### ISSUE TITLE
Soft Q-Learning 논문 소개

### ISSUE THREAD

**Issue by OPAYA** [kairproject/schedule#26]
논문이 아직 이해가 잘 되질 않아 계속해서 읽겠습니다!!

**Comment by Curt-Park** [comment]
@OPAYA 제목에 시간기입 부탁드립니다. 이번 주에는 개인당 15분이 배정되었으니 제목 앞에 [15분]을 붙이시면 됩니다.

더불어 이슈의 assignee에 본인을 할당해주세요~
