### ISSUE TITLE
[15분] Code implementation of Hindsight experience replay (HER) 

### ISSUE THREAD

**Issue by mch5048** [kairproject/schedule#28]
naive DDPG 와 DDPG+HER 의 script 구조적 차이를 설명드리고

 가능하면 실험적인 성능차이를 소개하드립니다.

** 진우님께서 말씀해주신 4가지 goal strategy를 웬만하면 다 구현해보는게 목표입니다.

**Comment by Curt-Park** [comment]
4가지 goal strategy 중에서도 final과 future에 더 큰 우선순위를 두고 구현해주시면 어떨까 싶습니다!
